#line 1 "CMDscan.cpp"

#line 3 "CMDscan.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer CMD_create_buffer
#define yy_delete_buffer CMD_delete_buffer
#define yy_scan_buffer CMD_scan_buffer
#define yy_scan_string CMD_scan_string
#define yy_scan_bytes CMD_scan_bytes
#define yy_init_buffer CMD_init_buffer
#define yy_flush_buffer CMD_flush_buffer
#define yy_load_buffer_state CMD_load_buffer_state
#define yy_switch_to_buffer CMD_switch_to_buffer
#define yypush_buffer_state CMDpush_buffer_state
#define yypop_buffer_state CMDpop_buffer_state
#define yyensure_buffer_stack CMDensure_buffer_stack
#define yy_flex_debug CMD_flex_debug
#define yyin CMDin
#define yyleng CMDleng
#define yylex CMDlex
#define yylineno CMDlineno
#define yyout CMDout
#define yyrestart CMDrestart
#define yytext CMDtext
#define yywrap CMDwrap
#define yyalloc CMDalloc
#define yyrealloc CMDrealloc
#define yyfree CMDfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define CMD_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer CMD_create_buffer
#endif

#ifdef yy_delete_buffer
#define CMD_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer CMD_delete_buffer
#endif

#ifdef yy_scan_buffer
#define CMD_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer CMD_scan_buffer
#endif

#ifdef yy_scan_string
#define CMD_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string CMD_scan_string
#endif

#ifdef yy_scan_bytes
#define CMD_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes CMD_scan_bytes
#endif

#ifdef yy_init_buffer
#define CMD_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer CMD_init_buffer
#endif

#ifdef yy_flush_buffer
#define CMD_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer CMD_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define CMD_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state CMD_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define CMD_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer CMD_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define CMDpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state CMDpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define CMDpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state CMDpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define CMDensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack CMDensure_buffer_stack
#endif

#ifdef yylex
#define CMDlex_ALREADY_DEFINED
#else
#define yylex CMDlex
#endif

#ifdef yyrestart
#define CMDrestart_ALREADY_DEFINED
#else
#define yyrestart CMDrestart
#endif

#ifdef yylex_init
#define CMDlex_init_ALREADY_DEFINED
#else
#define yylex_init CMDlex_init
#endif

#ifdef yylex_init_extra
#define CMDlex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra CMDlex_init_extra
#endif

#ifdef yylex_destroy
#define CMDlex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy CMDlex_destroy
#endif

#ifdef yyget_debug
#define CMDget_debug_ALREADY_DEFINED
#else
#define yyget_debug CMDget_debug
#endif

#ifdef yyset_debug
#define CMDset_debug_ALREADY_DEFINED
#else
#define yyset_debug CMDset_debug
#endif

#ifdef yyget_extra
#define CMDget_extra_ALREADY_DEFINED
#else
#define yyget_extra CMDget_extra
#endif

#ifdef yyset_extra
#define CMDset_extra_ALREADY_DEFINED
#else
#define yyset_extra CMDset_extra
#endif

#ifdef yyget_in
#define CMDget_in_ALREADY_DEFINED
#else
#define yyget_in CMDget_in
#endif

#ifdef yyset_in
#define CMDset_in_ALREADY_DEFINED
#else
#define yyset_in CMDset_in
#endif

#ifdef yyget_out
#define CMDget_out_ALREADY_DEFINED
#else
#define yyget_out CMDget_out
#endif

#ifdef yyset_out
#define CMDset_out_ALREADY_DEFINED
#else
#define yyset_out CMDset_out
#endif

#ifdef yyget_leng
#define CMDget_leng_ALREADY_DEFINED
#else
#define yyget_leng CMDget_leng
#endif

#ifdef yyget_text
#define CMDget_text_ALREADY_DEFINED
#else
#define yyget_text CMDget_text
#endif

#ifdef yyget_lineno
#define CMDget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno CMDget_lineno
#endif

#ifdef yyset_lineno
#define CMDset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno CMDset_lineno
#endif

#ifdef yywrap
#define CMDwrap_ALREADY_DEFINED
#else
#define yywrap CMDwrap
#endif

#ifdef yyalloc
#define CMDalloc_ALREADY_DEFINED
#else
#define yyalloc CMDalloc
#endif

#ifdef yyrealloc
#define CMDrealloc_ALREADY_DEFINED
#else
#define yyrealloc CMDrealloc
#endif

#ifdef yyfree
#define CMDfree_ALREADY_DEFINED
#else
#define yyfree CMDfree
#endif

#ifdef yytext
#define CMDtext_ALREADY_DEFINED
#else
#define yytext CMDtext
#endif

#ifdef yyleng
#define CMDleng_ALREADY_DEFINED
#else
#define yyleng CMDleng
#endif

#ifdef yyin
#define CMDin_ALREADY_DEFINED
#else
#define yyin CMDin
#endif

#ifdef yyout
#define CMDout_ALREADY_DEFINED
#else
#define yyout CMDout
#endif

#ifdef yy_flex_debug
#define CMD_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug CMD_flex_debug
#endif

#ifdef yylineno
#define CMDlineno_ALREADY_DEFINED
#else
#define yylineno CMDlineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 117
#define YY_END_OF_BUFFER 118
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[308] =
    {   0,
        0,    0,  118,  116,    1,    5,    4,   52,  116,  116,
       59,   58,  116,   42,   43,   46,   44,   57,   45,   51,
       47,  113,  113,   53,   54,   48,   62,   49,   39,   37,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,   40,   41,   60,   55,
       50,   56,   61,    1,    5,    0,    9,    0,    6,    0,
        0,   17,  110,   25,   12,   26,    0,    7,    0,   23,
       16,   21,   15,   22,   31,   33,  114,   38,    3,   24,
        0,  113,    0,    0,   14,   19,   11,    8,   10,   20,
      111,  111,  111,  111,  111,  111,  111,   72,  111,  111,

      111,  111,   73,   63,  111,  111,   34,   66,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,   27,
       28,   13,   18,  115,  110,    0,   32,    3,    3,  114,
        0,  114,  112,   29,   30,  111,  111,  111,  111,  111,
      111,  111,  111,   76,  111,  111,   79,  111,  111,  111,
      111,  111,   36,  111,  111,  111,   35,  111,  111,  115,
        0,    3,    2,  111,  111,   82,  111,  111,  111,   69,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
       65,  111,  108,  111,    3,    0,  111,   67,  111,  111,
      111,  109,  111,  111,    0,  111,   87,   64,  111,  111,

      111,  111,   71,    0,   70,  111,  111,  111,  111,  111,
        0,  111,   88,   68,  111,  111,   84,    0,  111,  111,
       85,   75,  111,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   86,  111,   89,   83,    0,   77,  111,
       74,   78,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  111,
        0,   81,    0,    0,    0,   95,    0,    0,    0,    0,
        0,  102,  101,  104,    0,   94,    0,    0,    0,   80,
       96,   92,    0,   93,    0,  100,    0,  106,    0,    0,
       98,   97,  103,  105,   91,    0,    0,    0,   99,    0,

        0,   90,    0,    0,    0,  107,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       20,   20,   20,   20,   20,   20,   20,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   38,   50,   51,   38,   52,
       53,   54,   55,   56,   38,    1,   57,   58,   59,   60,

       61,   62,   63,   64,   65,   38,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,   76,   38,   77,   78,
       38,   79,   80,   81,   82,   83,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[84] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    5,    5,
        5,    6,    1,    1,    7,    1,    1,    1,    5,    5,
        5,    5,    5,    5,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[322] =
    {   0,
        0,    0,  541,  675,  535,    0,  675,   77,   79,   67,
       70,   84,   84,  675,  675,  422,   82,  675,   85,   95,
       95,  102,  107,  411,  675,   73,  402,   74,  675,  675,
       56,   58,   89,  108,   77,  100,    0,  105,   77,  112,
      102,  125,  127,  146,  135,  122,  675,  675,  390,  675,
       80,  675,  675,  409,    0,  383,  675,  149,  675,  345,
      180,  675,  293,  675,  675,  675,  152,  675,  307,  675,
      675,  675,  280,  675,  675,  675,  193,  675,  284,  675,
      199,  205,  213,    0,  675,  273,  675,  675,  675,  234,
        0,  103,  154,  119,  147,  156,  168,    0,  162,  170,

      182,  193,    0,    0,  192,  191,    0,    0,  211,  206,
      203,  198,  205,  217,  216,  213,  221,  204,  217,  675,
      675,  675,  675,  230,  222,  217,  675,    0,  257,  264,
      237,  267,    0,  675,  675,  231,  236,  248,  221,  260,
      262,  261,  252,  262,  269,  265,    0,  264,  262,  270,
      258,  273,    0,  273,  268,  265,    0,  281,  276,  185,
      183,  317,  341,  278,  288,    0,  281,  302,  286,    0,
      304,  312,  299,  175,  319,  302,  319,  309,  316,  315,
        0,  322,    0,  325,  360,  177,  313,    0,  324,  327,
      328,    0,  339,  334,  169,  337,  339,    0,  333,  345,

      337,  343,    0,  167,    0,  338,  346,  342,  355,  353,
      395,  359,    0,    0,  355,  363,  165,  401,  376,  379,
        0,  135,  371,  370,  388,  424,  387,  389,  419,  401,
      417,  438,  430,    0,  408,    0,  675,  469,    0,  428,
      675,    0,  448,  443,  456,  435,  456,  445,  446,  438,
      447,  444,  454,  447,  456,  457,  457,  455,  460,  462,
      508,    0,  465,  478,  478,  675,  474,  487,  500,  500,
      491,  675,  675,  675,  504,  675,  495,  491,  504,    0,
      115,  675,  498,  675,  497,  675,  498,  675,  504,  501,
      675,  675,  675,  675,  675,  507,  510,  516,  675,  519,

      508,  675,  508,  525,  519,  675,  675,  590,  598,  602,
      610,  614,  618,  622,  630,  120,  634,  642,  650,  658,
      666
    } ;

static const flex_int16_t yy_def[322] =
    {   0,
      307,    1,  307,  307,  307,  308,  307,  307,  309,  310,
      310,  307,  311,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  307,  307,  307,  307,
      307,  307,  307,  307,  308,  307,  307,  309,  307,  309,
      313,  307,  314,  307,  307,  307,  311,  307,  311,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  315,  307,
      307,  307,  307,  316,  307,  307,  307,  307,  307,  307,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  307,
      307,  307,  307,  317,  314,  314,  307,  315,  318,  307,
      307,  307,  316,  307,  307,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  317,
      317,  319,  307,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  319,  307,  312,  312,  312,  312,
      312,  312,  312,  312,  307,  312,  312,  312,  312,  312,

      312,  312,  312,  307,  312,  312,  312,  312,  312,  312,
      307,  312,  312,  312,  312,  312,  312,  320,  312,  312,
      312,  312,  312,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  312,  312,  312,  307,  321,  312,  312,
      307,  312,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  312,
      321,  312,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  312,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,    0,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307
    } ;

static const flex_int16_t yy_nxt[759] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   37,   38,   37,   37,   37,
       39,   40,   41,   42,   37,   43,   44,   45,   37,   46,
       37,   37,   47,    4,   48,   49,   31,   32,   33,   34,
       35,   36,   37,   37,   38,   37,   37,   39,   40,   41,
       42,   37,   43,   44,   45,   37,   46,   37,   37,   50,
       51,   52,   53,   56,   59,   61,   61,   61,   61,   61,
       61,   62,   65,   68,   64,   71,   86,   87,   89,   90,

       73,   57,   92,   93,  121,  105,   72,   78,   66,   74,
       75,   76,   79,   77,   77,   77,   99,   94,   81,   80,
       82,   82,   82,   81,  133,   82,   82,   82,  100,   92,
       93,   95,   60,  105,   83,  293,   96,   69,  103,   83,
       97,  241,  101,   99,  106,   94,  104,  108,  102,  136,
       98,  107,   84,  109,   59,  111,  100,  119,   95,  112,
      122,   68,   83,  117,   96,  138,  103,   83,   97,  101,
      110,  237,  106,  104,  108,  102,  136,   98,  107,   84,
      118,  109,  113,  111,  218,  119,  137,  112,  139,  114,
      211,  117,  138,  115,  204,  116,  195,  110,   61,   61,

       61,  141,   60,  140,  161,   69,  161,  118,  142,  143,
      113,   77,   77,   77,  137,  139,  114,  130,  130,  130,
      115,   81,  116,   82,   82,   82,  131,  144,  131,  141,
      140,  132,  132,  132,  145,  142,  143,   83,  126,  146,
      147,  148,  149,  126,  150,  151,  152,  153,  155,  156,
      157,  161,  158,  159,  144,  132,  132,  132,  135,  163,
      163,  145,  154,  164,  165,   83,  146,  147,  167,  148,
      149,  150,  151,  152,  128,  153,  155,  156,  157,  158,
      166,  159,  130,  130,  130,  132,  132,  132,  168,  154,
      169,  164,  165,  170,  172,  167,   83,  134,  171,  173,

      174,  129,  175,  176,  177,  127,  178,  179,  166,  180,
       67,  181,  182,  183,  126,  184,  168,  189,  169,  163,
      163,  170,  172,  187,   83,  171,  188,  173,  174,  175,
      176,  190,  177,  178,  191,  179,  192,  180,  181,  182,
      193,  183,  184,  163,  163,  189,  194,  196,   58,  197,
      187,  198,  202,  188,  199,  200,  201,  203,  186,  190,
      205,  191,  163,  163,  192,  206,  207,  208,  193,  209,
      210,  212,  213,  194,  214,  196,  197,  215,  217,  198,
      202,  199,  200,  201,  216,  203,  219,  205,  220,  221,
      222,  234,  206,  207,  208,  223,  236,  209,  210,  212,

      213,  214,  235,  163,  163,  215,  217,  123,  239,  240,
       54,  216,  242,  219,  120,  220,  221,  243,  222,  234,
      244,  251,  223,  224,  236,  225,   88,  245,  226,  235,
      246,  227,   85,  250,  228,  229,  239,  240,  230,  242,
      231,  232,  233,  254,  243,  255,   70,  252,  244,  251,
      260,  224,  247,  225,  245,  253,  226,  246,  259,  227,
      250,  228,  229,  248,  249,  230,  262,  231,  232,  233,
      254,  163,  163,  255,  256,  252,  263,  260,  257,  264,
      247,  266,  258,  253,  265,  267,  259,  268,  269,  270,
      248,  249,  271,  262,  272,  273,  274,  275,  276,  277,

      278,  279,  256,  280,  263,  257,  281,  264,  266,  258,
      163,  163,  265,  267,  268,  269,  270,  282,  283,  271,
      284,  272,  273,  274,  275,  276,  277,  278,  279,  285,
      280,  286,  287,  281,  288,  289,   54,  290,  291,  292,
      307,  294,  295,  296,  282,  283,  297,  284,  298,  299,
      300,  301,  302,  307,  303,  304,  285,  305,  307,  286,
      287,  288,  306,  289,  290,  291,  307,  292,  294,  295,
      296,  307,  307,  297,  307,  298,  299,  300,  307,  301,
      302,  303,  304,  307,  307,  305,  307,  307,  307,  306,
       55,  307,   55,   55,   55,   55,   55,   55,   58,  307,

      307,   58,   58,   58,   58,   58,   63,  307,   63,   63,
       67,  307,  307,   67,   67,   67,   67,   67,   91,  307,
      307,   91,  124,  307,  307,  124,  125,  125,  307,  125,
      128,  307,  307,  128,  128,  128,  128,  128,  160,  160,
      307,  160,  162,  162,  162,  162,  162,  162,  162,  162,
      185,  185,  185,  185,  185,  185,  185,  185,  238,  238,
      238,  307,  238,  238,  238,  238,  261,  261,  261,  261,
      261,  261,  261,  261,    3,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307
    } ;

static const flex_int16_t yy_chk[759] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,    9,   10,   10,   10,   11,   11,
       11,   10,   12,   13,   11,   17,   26,   26,   28,   28,

       19,    8,   31,   32,   51,   39,   17,   21,   12,   19,
       19,   20,   21,   20,   20,   20,   35,   33,   22,   21,
       22,   22,   22,   23,  316,   23,   23,   23,   36,   31,
       32,   33,    9,   39,   22,  281,   34,   13,   38,   23,
       34,  222,   36,   35,   40,   33,   38,   41,   36,   92,
       34,   40,   22,   42,   58,   43,   36,   46,   33,   43,
       51,   67,   22,   45,   34,   94,   38,   23,   34,   36,
       42,  217,   40,   38,   41,   36,   92,   34,   40,   22,
       45,   42,   44,   43,  204,   46,   93,   43,   95,   44,
      195,   45,   94,   44,  186,   44,  174,   42,   61,   61,

       61,   97,   58,   96,  161,   67,  160,   45,   99,  100,
       44,   77,   77,   77,   93,   95,   44,   81,   81,   81,
       44,   82,   44,   82,   82,   82,   83,  101,   83,   97,
       96,   83,   83,   83,  102,   99,  100,   82,  126,  105,
      106,  109,  110,  125,  111,  112,  113,  114,  115,  116,
      117,  124,  118,  119,  101,  131,  131,  131,   90,  129,
      129,  102,  114,  136,  137,   82,  105,  106,  139,  109,
      110,  111,  112,  113,  129,  114,  115,  116,  117,  118,
      138,  119,  130,  130,  130,  132,  132,  132,  140,  114,
      141,  136,  137,  142,  144,  139,  130,   86,  143,  145,

      146,   79,  148,  149,  150,   73,  151,  152,  138,  154,
       69,  155,  156,  158,   63,  159,  140,  167,  141,  162,
      162,  142,  144,  164,  130,  143,  165,  145,  146,  148,
      149,  168,  150,  151,  169,  152,  171,  154,  155,  156,
      172,  158,  159,  163,  163,  167,  173,  175,   60,  176,
      164,  177,  182,  165,  178,  179,  180,  184,  163,  168,
      187,  169,  185,  185,  171,  189,  190,  191,  172,  193,
      194,  196,  197,  173,  199,  175,  176,  200,  202,  177,
      182,  178,  179,  180,  201,  184,  206,  187,  207,  208,
      209,  212,  189,  190,  191,  210,  216,  193,  194,  196,

      197,  199,  215,  218,  218,  200,  202,   56,  219,  220,
       54,  201,  223,  206,   49,  207,  208,  224,  209,  212,
      225,  228,  210,  211,  216,  211,   27,  225,  211,  215,
      225,  211,   24,  227,  211,  211,  219,  220,  211,  223,
      211,  211,  211,  230,  224,  231,   16,  229,  225,  228,
      235,  211,  226,  211,  225,  229,  211,  225,  233,  211,
      227,  211,  211,  226,  226,  211,  240,  211,  211,  211,
      230,  238,  238,  231,  232,  229,  243,  235,  232,  244,
      226,  246,  232,  229,  245,  247,  233,  248,  249,  250,
      226,  226,  251,  240,  252,  253,  254,  255,  256,  257,

      258,  259,  232,  260,  243,  232,  263,  244,  246,  232,
      261,  261,  245,  247,  248,  249,  250,  264,  265,  251,
      267,  252,  253,  254,  255,  256,  257,  258,  259,  268,
      260,  269,  270,  263,  271,  275,    5,  277,  278,  279,
        3,  283,  285,  287,  264,  265,  289,  267,  290,  296,
      297,  298,  300,    0,  301,  303,  268,  304,    0,  269,
      270,  271,  305,  275,  277,  278,    0,  279,  283,  285,
      287,    0,    0,  289,    0,  290,  296,  297,    0,  298,
      300,  301,  303,    0,    0,  304,    0,    0,    0,  305,
      308,    0,  308,  308,  308,  308,  308,  308,  309,    0,

        0,  309,  309,  309,  309,  309,  310,    0,  310,  310,
      311,    0,    0,  311,  311,  311,  311,  311,  312,    0,
        0,  312,  313,    0,    0,  313,  314,  314,    0,  314,
      315,    0,    0,  315,  315,  315,  315,  315,  317,  317,
        0,  317,  318,  318,  318,  318,  318,  318,  318,  318,
      319,  319,  319,  319,  319,  319,  319,  319,  320,  320,
      320,    0,  320,  320,  320,  320,  321,  321,  321,  321,
      321,  321,  321,  321,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[118] =
    {   0,
0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "CMDscan.l"
/* ElfScript 0.7: Added caseless */
#line 4 "CMDscan.l"

// flex --nounput -o CMDscan.cpp -P CMD CMDscan.l

#define YYLMAX 4096
#define YY_NO_UNISTD_H

#include <stdio.h>
#include "platform/platform.h"
#include "core/stringTable.h"
#include "console/console.h"
#include "console/torquescript/compiler.h"
#include "console/dynamicTypes.h"
#include "core/strings/stringFunctions.h"

// ElfScript was double defined!!, but i need it :/ =>
template< typename T >
struct Token
{
   T value;
   S32 lineNumber;
};

// Can't have ctors in structs used in unions, so we have this.
template< typename T >
inline Token< T > MakeToken( T value, S32 lineNumber )
{
   Token< T > result;
   result.value = value;
   result.lineNumber = lineNumber;
   return result;
}

#include "console/torquescript/CMDgram.h"

// HACK: C++17 and beyond can't use register keyword
#define register

using namespace Compiler;

#define YY_NEVER_INTERACTIVE 1

// Some basic parsing primitives...
static int Sc_ScanDocBlock();
static int Sc_ScanString(int ret);
static int Sc_ScanNum();
static int Sc_ScanVar();
static int Sc_ScanHex();
static int Sc_ScanIdent();

// Deal with debuggability of FLEX.
#ifdef TORQUE_DEBUG
#define FLEX_DEBUG 1
#else
#define FLEX_DEBUG 0
#endif

Vector<String> lines;
static S32 gCachedLineContextCount = -1;   // -1 = needs refresh

static S32 getLineContextCount()
{
   if (gCachedLineContextCount < 0)
      gCachedLineContextCount = Con::getIntVariable("$scriptErrorLineCount", 10);
   return gCachedLineContextCount;
}

void CMDFlushLineContextCache()
{
   gCachedLineContextCount = -1;
}

// Install our own input code...
#undef CMDgetc
int CMDgetc();

// Hack to make windows lex happy.
#ifndef isatty
inline int isatty(int) { return 0; }
#endif

static int yycolumn = 1;

#define YY_INPUT(buf, result, max_size)                          \
   {                                                             \
      int c = '*', n;                                            \
      for (n = 0; n < max_size &&                                \
           (c = CMDgetc()) != EOF && c != '\n'; ++n)             \
         buf[n] = (char)c;                                       \
      if (c == '\n') { buf[n++] = (char)c; yycolumn = 1; }       \
      result = n;                                                \
   }

#define YY_USER_ACTION                                           \
   do {                                                          \
      CMDlloc.first_line   = CMDlloc.last_line   = yylineno;     \
      CMDlloc.first_column = yycolumn;                           \
      CMDlloc.last_column  = yycolumn + yyleng - 1;              \
      yycolumn += yyleng;                                        \
   } while (0);

// File state
void CMDSetScanBuffer(const char *sb, const char *fn);

// Error reporting
void CMDerror(const char * s, ...);

// Reset the parser.
void CMDrestart(FILE *in);

#line 1115 "CMDscan.cpp"
#line 1116 "CMDscan.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 130 "CMDscan.l"


#line 1334 "CMDscan.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 308 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 675 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 132 "CMDscan.l"
{ /* consume whitespace */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 134 "CMDscan.l"
{ return Sc_ScanDocBlock(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 135 "CMDscan.l"
{ /* line comment — discard */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 136 "CMDscan.l"
{ /* bare CR — discard */ }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 138 "CMDscan.l"
{
   yycolumn = 1;

   // Push the line text (everything after the newline) into the error
   // context buffer, then trim to the configured maximum.
   lines.push_back(String::ToString("%s", yytext + 1));
   S32 maxLines = getLineContextCount();
   while (lines.size() > maxLines)
      lines.erase(lines.begin());

   yyless(1);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 151 "CMDscan.l"
{ return Sc_ScanString(STRATOM); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 152 "CMDscan.l"
{ return Sc_ScanString(TAGATOM); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 154 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opEQ,          yylineno); return opEQ;          }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 155 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opNE,          yylineno); return opNE;          }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 156 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opGE,          yylineno); return opGE;          }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 157 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opLE,          yylineno); return opLE;          }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 158 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opAND,         yylineno); return opAND;         }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 159 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opOR,          yylineno); return opOR;          }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 160 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opCOLONCOLON,  yylineno); return opCOLONCOLON; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 161 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opMINUSMINUS,  yylineno); return opMINUSMINUS;  }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 162 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opPLUSPLUS,    yylineno); return opPLUSPLUS;    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 163 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opSTREQ,       yylineno); return opSTREQ;       }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 164 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opSTRNE,       yylineno); return opSTRNE;       }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 165 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opSHL,         yylineno); return opSHL;         }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 166 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opSHR,         yylineno); return opSHR;         }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 167 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opPLASN,       yylineno); return opPLASN;       }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 168 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opMIASN,       yylineno); return opMIASN;       }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 169 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opMLASN,       yylineno); return opMLASN;       }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 170 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opDVASN,       yylineno); return opDVASN;       }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 171 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opMODASN,      yylineno); return opMODASN;      }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 172 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opANDASN,      yylineno); return opANDASN;      }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 173 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opXORASN,      yylineno); return opXORASN;      }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 174 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opORASN,       yylineno); return opORASN;       }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 175 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opSLASN,       yylineno); return opSLASN;       }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 176 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opSRASN,       yylineno); return opSRASN;       }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 177 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opINTNAME,     yylineno); return opINTNAME;     }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 178 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opINTNAMER,    yylineno); return opINTNAMER;    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 179 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(opDOTDOT,      yylineno); return opDOTDOT;      }
	YY_BREAK

// String concatenation operators.  All four return the '@' token; the
// distinguishing data is the separator character stored in the token value.
// The grammar rule  expr '@' expr  uses $2.value as the appendChar
// argument to StrcatExprNode — so plain '@' gets 0 (no separator),
// NL/TAB/SPC get their respective ASCII codes.

case 34:
YY_RULE_SETUP
#line 187 "CMDscan.l"
{ CMDlval.i = MakeToken<int>('\n', yylineno); return '@'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 188 "CMDscan.l"
{ CMDlval.i = MakeToken<int>('\t', yylineno); return '@'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 189 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(' ',  yylineno); return '@'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 190 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(0,    yylineno); return '@'; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 192 "CMDscan.l"
{
   // Block comment — consume until '*/'
   int c = 0, prev = 0;
   for (;;)
   {
      prev = c;
      c    = yyinput();
      if (c == EOF)
      {
         CMDerror("unexpected end of file inside block comment");
         break;
      }
      if (prev == '*' && c == '/')
         break;
   }
}
	YY_BREAK

// Single-character punctuation tokens.

case 39:
#line 212 "CMDscan.l"
case 40:
#line 213 "CMDscan.l"
case 41:
#line 214 "CMDscan.l"
case 42:
#line 215 "CMDscan.l"
case 43:
#line 216 "CMDscan.l"
case 44:
#line 217 "CMDscan.l"
case 45:
#line 218 "CMDscan.l"
case 46:
#line 219 "CMDscan.l"
case 47:
#line 220 "CMDscan.l"
case 48:
#line 221 "CMDscan.l"
case 49:
#line 222 "CMDscan.l"
case 50:
#line 223 "CMDscan.l"
case 51:
#line 224 "CMDscan.l"
case 52:
#line 225 "CMDscan.l"
case 53:
#line 226 "CMDscan.l"
case 54:
#line 227 "CMDscan.l"
case 55:
#line 228 "CMDscan.l"
case 56:
#line 229 "CMDscan.l"
case 57:
#line 230 "CMDscan.l"
case 58:
#line 231 "CMDscan.l"
case 59:
#line 232 "CMDscan.l"
case 60:
#line 233 "CMDscan.l"
case 61:
#line 234 "CMDscan.l"
case 62:
YY_RULE_SETUP
#line 234 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(CMDtext[0], yylineno); return CMDtext[0]; }
	YY_BREAK

// Reserved words — must be listed before {ID} to take priority.
// NOTE: "namespace" and "class" are intentionally NOT listed here.
// rwNAMESPACE and rwCLASS were previously declared as grammar tokens but
// had no productions that used them and no lexer rules that produced them.
// They have been removed from the grammar.  The words "namespace" and
// "class" therefore lex as plain IDENT tokens and can be used as object
// names or field names in script without causing parse errors.  If you add
// syntax that consumes those keywords, add both the lexer rule and the
// grammar token declaration at the same time.

// ElfScript 0.6: added blank on range and step since i have methods which are named like that ...
//                hope this is a good idea

case 63:
YY_RULE_SETUP
#line 249 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwIN,               yylineno); return rwIN;               }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 250 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwRANGE,            yylineno); return rwRANGE;            }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 251 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwSTEP,             yylineno); return rwSTEP;             }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 253 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwCASEOR,           yylineno); return rwCASEOR;           }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 254 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwBREAK,            yylineno); return rwBREAK;            }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 255 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwRETURN,           yylineno); return rwRETURN;           }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 256 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwELSE,             yylineno); return rwELSE;             }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 257 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwASSERT,           yylineno); return rwASSERT;           }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 258 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwWHILE,            yylineno); return rwWHILE;            }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 259 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwDO,               yylineno); return rwDO;               }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 260 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwIF,               yylineno); return rwIF;               }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 261 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwFOREACHSTR,       yylineno); return rwFOREACHSTR;       }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 262 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwFOREACH,          yylineno); return rwFOREACH;          }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 263 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwFOR,              yylineno); return rwFOR;              }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 264 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwCONTINUE,         yylineno); return rwCONTINUE;         }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 265 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwDEFINE,           yylineno); return rwDEFINE;           }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 266 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwDECLARE,          yylineno); return rwDECLARE;          }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 267 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwDECLARESINGLETON, yylineno); return rwDECLARESINGLETON; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 268 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwDATABLOCK,        yylineno); return rwDATABLOCK;        }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 269 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwCASE,             yylineno); return rwCASE;             }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 270 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwSWITCHSTR,        yylineno); return rwSWITCHSTR;        }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 271 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwSWITCH,           yylineno); return rwSWITCH;           }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 272 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwDEFAULT,          yylineno); return rwDEFAULT;          }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 273 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwPACKAGE,          yylineno); return rwPACKAGE;          }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 274 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwPRINT,            yylineno); return rwPRINT;          }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 275 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwPRINTF,            yylineno); return rwPRINTF;          }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 276 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwSPRINTF,            yylineno); return rwSPRINTF;          }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 277 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwRANDOMF,          yylineno); return rwRANDOMF;          }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 279 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwFLOOR,            yylineno); return rwFLOOR;          }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 280 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwCEIL,             yylineno); return rwCEIL;          }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 281 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwFABS,             yylineno); return rwFABS;          }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 282 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwSIN,              yylineno); return rwSIN;          }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 283 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwCOS,              yylineno); return rwCOS;          }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 284 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwATAN,             yylineno); return rwATAN;          }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 285 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwTANH,             yylineno); return rwTANH;          }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 286 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwSQRT,             yylineno); return rwSQRT;          }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 287 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwISZERO,           yylineno); return rwISZERO;          }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 289 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwFMOD,             yylineno); return rwFMOD;          }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 290 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwMIN,              yylineno); return rwMIN;          }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 291 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwMAX,              yylineno); return rwMAX;          }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 292 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwATAN2,            yylineno); return rwATAN2;          }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 293 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwPOW,              yylineno); return rwPOW;          }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 295 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwCLAMPF,         yylineno); return rwCLAMPF;          }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 296 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwLERP,           yylineno); return rwLERP;          }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 297 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(rwSMOOTHSTEP,     yylineno); return rwSMOOTHSTEP;          }
	YY_BREAK

// Boolean literals — return INTCONST so the parser treats them as integers.

case 108:
YY_RULE_SETUP
#line 301 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(1, yylineno); return INTCONST; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 302 "CMDscan.l"
{ CMDlval.i = MakeToken<int>(0, yylineno); return INTCONST; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 304 "CMDscan.l"
{ return Sc_ScanVar(); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 305 "CMDscan.l"
{ return Sc_ScanIdent(); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 306 "CMDscan.l"
{ return Sc_ScanHex(); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 307 "CMDscan.l"
{ CMDtext[CMDleng] = 0;
                        CMDlval.i = MakeToken<int>(dAtoi(CMDtext), yylineno);
                        return INTCONST; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 310 "CMDscan.l"
{ return Sc_ScanNum(); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 311 "CMDscan.l"
{ return ILLEGAL_TOKEN; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 312 "CMDscan.l"
{ return ILLEGAL_TOKEN; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 313 "CMDscan.l"
ECHO;
	YY_BREAK
#line 1974 "CMDscan.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 308 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 308 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 307);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 313 "CMDscan.l"


static const char *scanBuffer;
static const char *fileName;
static int scanIndex;
extern YYLTYPE CMDlloc;

const char* CMDGetCurrentFile()  { return fileName; }
int         CMDGetCurrentLine()  { return yylineno; }

void CMDSetScanBuffer(const char* sb, const char* fn)
{
   scanBuffer              = sb;
   fileName                = fn;
   scanIndex               = 0;
   yylineno                = 1;
   gCachedLineContextCount = -1;   // re-read $scriptErrorLineCount for each file
   lines.clear();
}

int CMDgetc()
{
   int c = scanBuffer[scanIndex];
   if (c)
      scanIndex++;
   else
      c = -1;  // EOF sentinel expected by YY_INPUT
   return c;
}

int CMDwrap()
{
   return 1;
}

extern bool gConsoleSyntaxError;

void CMDerror(const char* format, ...)
{
   Compiler::gSyntaxError = true;

   const int BUFMAX = 1024;
   char tempBuf[BUFMAX];
   va_list args;
   va_start(args, format);
#ifdef TORQUE_OS_WIN
   _vsnprintf(tempBuf, BUFMAX, format, args);
#else
   vsnprintf(tempBuf, BUFMAX, format, args);
#endif
   va_end(args);

   if (fileName)
   {
      Con::errorf(ConsoleLogEntry::Script, "%s Line: %d - %s",
                  fileName, yylineno, tempBuf);

      // Append to the script-visible error string and bump the hash so
      // listeners know a new error arrived.
      const char* prevStr = Con::getVariable("$ScriptError");
      if (prevStr[0])
         dSprintf(tempBuf, sizeof(tempBuf), "%s\n%s Line: %d - Syntax error.",
                  prevStr, fileName, yylineno);
      else
         dSprintf(tempBuf, sizeof(tempBuf), "%s Line: %d - Syntax error.",
                  fileName, yylineno);
      Con::setVariable("$ScriptError", tempBuf);

      static S32 sScriptErrorHash = 1000;
      Con::setIntVariable("$ScriptErrorHash", sScriptErrorHash++);
   }
   else
   {
      Con::errorf(ConsoleLogEntry::Script, tempBuf);
   }
}

static int Sc_ScanVar()
{
   // Truncate the temp buffer...
   CMDtext[CMDleng] = 0;

   // Make it a stringtable string!
   CMDlval.s = MakeToken< StringTableEntry >( StringTable->insert(CMDtext), yylineno );
   return(VAR);
}

static int charConv(int in)
{
   switch (in)
   {
   case 'r': return '\r';
   case 'n': return '\n';
   case 't': return '\t';
   default:  return in;
   }
}

static int getHexDigit(char c)
{
   if (c >= '0' && c <= '9') return c - '0';
   if (c >= 'A' && c <= 'F') return c - 'A' + 10;
   if (c >= 'a' && c <= 'f') return c - 'a' + 10;
   return -1;
}

static int Sc_ScanDocBlock()
{
   S32   len  = dStrlen(CMDtext);
   char* text = (char*)consoleAlloc(len + 1);
   S32   line = yylineno;

   for (S32 i = 0, j = 0; j <= len; j++)
   {
      // Strip leading '///' on each doc line.
      if ((j <= (len - 2)) &&
          CMDtext[j]     == '/' &&
          CMDtext[j + 1] == '/' &&
          CMDtext[j + 2] == '/')
      {
         j += 2;
         continue;
      }
      if (CMDtext[j] == '\r') continue;
      text[i++] = CMDtext[j];
   }

   CMDlval.str = MakeToken<char*>(text, line);
   return DOCBLOCK;
}

static int Sc_ScanString(int ret)
{
   // CMDtext arrives as  "content"  or  'content'  (with quotes).
   // Replace the closing quote with a null terminator so collapseEscape
   // can work on the interior without seeing the delimiter.
   CMDtext[CMDleng - 1] = '\0';
   if (!collapseEscape(CMDtext + 1))
      return -1; 

   dsize_t allocSize = dStrlen(CMDtext);   // = 1 + content_len  (see above)
   char*   buffer    = (char*)consoleAlloc(allocSize);
   dStrcpy(buffer, CMDtext + 1, allocSize);   // skip the opening quote

   CMDlval.str = MakeToken< char* >( buffer, yylineno );
   return ret;
}

static int Sc_ScanIdent()
{
   CMDtext[CMDleng] = 0;

   // Check if the identifier is a registered engine type name (e.g. "Point3F").
   ConsoleBaseType* type = ConsoleBaseType::getTypeByName(CMDtext);
   if (type)
   {
      CMDlval.i = MakeToken<int>(type->getTypeID(), yylineno);
      return TYPEIDENT;
   }

   CMDlval.s = MakeToken<StringTableEntry>(StringTable->insert(CMDtext), yylineno);
   return IDENT;
}

static int Sc_ScanNum()
{
   CMDtext[CMDleng] = 0;
   CMDlval.f = MakeToken<double>(dAtof(CMDtext), yylineno);
   return FLTCONST;
}

static int Sc_ScanHex()
{
   S32 val = 0;
   dSscanf(CMDtext, "%x", &val);
   CMDlval.i = MakeToken<int>(val, yylineno);
   return INTCONST;
}

void expandEscape(char *dest, const char *src)
{
   U8 c;
   while((c = (U8) *src++) != 0)
   {
      if(c == '\"')
      {
         *dest++ = '\\';
         *dest++ = '\"';
      }
      else if(c == '\\')
      {
         *dest++ = '\\';
         *dest++ = '\\';
      }
      else if(c == '\r')
      {
         *dest++ = '\\';
         *dest++ = 'r';
      }
      else if(c == '\n')
      {
         *dest++ = '\\';
         *dest++ = 'n';
      }
      else if(c == '\t')
      {
         *dest++ = '\\';
         *dest++ = 't';
      }
      else if(c == '\'')
      {
         *dest++ = '\\';
         *dest++ = '\'';
      }
      else if((c >= 1 && c <= 7) ||
              (c >= 11 && c <= 12) ||
              (c >= 14 && c <= 15))
      {
        /*  Remap around: \b = 0x8, \t = 0x9, \n = 0xa, \r = 0xd */
        static U8 expandRemap[15] = { 0x0,
                                        0x0,
                                        0x1,
                                        0x2,
                                        0x3,
                                        0x4,
                                        0x5,
                                        0x6,
                                        0x0,
                                        0x0,
                                        0x0,
                                        0x7,
                                        0x8,
                                        0x0,
                                        0x9 };

         *dest++ = '\\';
         *dest++ = 'c';
         if(c == 15)
            *dest++ = 'r';
         else if(c == 16)
            *dest++ = 'p';
         else if(c == 17)
            *dest++ = 'o';
         else
            *dest++ = expandRemap[c] + '0';
      }
      else if(c < 32)
      {
         *dest++ = '\\';
         *dest++ = 'x';
         S32 dig1 = c >> 4;
         S32 dig2 = c & 0xf;
         if(dig1 < 10)
            dig1 += '0';
         else
            dig1 += 'A' - 10;
         if(dig2 < 10)
            dig2 += '0';
         else
            dig2 += 'A' - 10;
         *dest++ = dig1;
         *dest++ = dig2;
      }
      else
         *dest++ = c;
   }
   *dest = '\0';
}

bool collapseEscape(char *buf)
{
   S32 len = dStrlen(buf) + 1;
   for(S32 i = 0; i < len;)
   {
      if(buf[i] == '\\')
      {
         if(buf[i+1] == 'x')
         {
            S32 dig1 = getHexDigit(buf[i+2]);
            if(dig1 == -1)
               return false;

            S32 dig2 = getHexDigit(buf[i+3]);
            if(dig2 == -1)
               return false;
            buf[i] = dig1 * 16 + dig2;
            dMemmove(buf + i + 1, buf + i + 4, len - i - 3);
            len -= 3;
            i++;
         }
         else if(buf[i+1] == 'c')
         {
            /*  Remap around: \b = 0x8, \t = 0x9, \n = 0xa, \r = 0xd */
            static U8 collapseRemap[10] = { 0x1,
                                              0x2,
                                              0x3,
                                              0x4,
                                              0x5,
                                              0x6,
                                              0x7,
                                              0xb,
                                              0xc,
                                              0xe };

            if(buf[i+2] == 'r')
                buf[i] = 15;
            else if(buf[i+2] == 'p')
               buf[i] = 16;
            else if(buf[i+2] == 'o')
               buf[i] = 17;
            else
            {
                int dig1 = buf[i+2] - '0';
                if(dig1 < 0 || dig1 > 9)
                   return false;
                buf[i] = collapseRemap[dig1];
            }
            // Make sure we don't put 0x1 at the beginning of the string.
            if ((buf[i] == 0x1) && (i == 0))
            {
               buf[i] = 0x2;
               buf[i+1] = 0x1;
               dMemmove(buf + i + 2, buf + i + 3, len - i - 1);
               len -= 1;
            }
            else
            {
               dMemmove(buf + i + 1, buf + i + 3, len - i - 2);
               len -= 2;
            }
            i++;
         }
         else
         {
            buf[i] = charConv(buf[i+1]);
            dMemmove(buf + i + 1, buf + i + 2, len - i - 1);
            len--;
            i++;
         }
      }
      else
         i++;
   }
   return true;
}

void CMD_reset()
{
   CMDrestart(NULL);
}

